In [1]:
import numpy as np
import pandas as pd

In [9]:
pd.Series([10, 100, 15, 35]) # index
np.array([10, 100, 15, 35]) # no index
print(type(pd.Series([10, 100, 15, 35])))

#print(type(dict))

<class 'pandas.core.series.Series'>

In [30]:
s1 = pd.Series([1,2,3,])
print(s1)
s1[0]  # key = 0

0    1
1    2
2    3
dtype: int64

1

In [51]:
countries = {
    'USA':    1776,
    'CANADA': 1867,
    'MEXICO': 1821
}
s = pd.Series(countries)
print(s)

USA       1776
CANADA    1867
MEXICO    1821
dtype: int64

In [22]:
years = [1776, 1867, 1821]
label_index = ['USA', 'CANADA', 'MEXICO']
pd.Series(years, label_index)
pd.Series(data=years, index=label_index)  
countries = pd.Series(data=years, index=label_index)  # better
countries
# create business card index f-name, l-name, city, country
# 1
# create series that looks like:
# f-name  Danny
# l-name  Shovevani
# city    Rehovot
# country Israel
# 2
# input the values from the user
# create the card from the input
f_name = input('Whats your name?')

USA       1776
CANADA    1867
MEXICO    1821
dtype: int64

In [35]:
years = [1776, 1867, 1821]
label_index = ['USA', 'CANADA', 'MEXICO']
countries = pd.Series(data=years, index=label_index) 

print(countries)
print(countries.keys())
print(countries.keys()[0])
print(list(countries.keys()))

# countries[KEY] == countries.loc[KEY]

# countries[0]  # bad -- because the index is Label and not number
countries.iloc[0]  # iloc = index location 
countries.loc['CANADA']
# countries.loc[1]  # error - no index 1 -- the index == Index(['USA', 'CANADA', 'MEXICO'], dtype='object')

USA       1776
CANADA    1867
MEXICO    1821
dtype: int64
Index(['USA', 'CANADA', 'MEXICO'], dtype='object')
USA
['USA', 'CANADA', 'MEXICO']

1867

In [36]:
first  = pd.Series({'Japan': 100, 'China': 450, 'USA': 250})
second = pd.Series({'Brazil': 70, 'China': 350, 'USA': 200})

result = first + second
print(result)

Brazil      NaN
China     800.0
Japan       NaN
USA       450.0
dtype: float64

In [37]:
first  = pd.Series({'Japan': 100, 'China': 450, 'USA': 250})
second = pd.Series({'Brazil': 70, 'China': 350, 'USA': 200})

result = first.add(second, fill_value=0)
print(result)

Brazil     70.0
China     800.0
Japan     100.0
USA       450.0
dtype: float64

In [40]:
first  = pd.Series({'Japan': 100.2, 'China': 450, 'USA': 250})
print(first.dtype)  # float64

first  = pd.Series({'Japan': 100, 'China': 450, 'USA': 250})
print(first.dtype)  # int64

print(first)

float64
Japan    100.2
China    450.0
USA      250.0
dtype: float64

In [42]:
first  = pd.Series({'Japan': 100.99, 'China': 450, 'USA': 250})
print(first.dtype) 
print(first.astype(int))

float64
Japan    100
China    450
USA      250
dtype: int32

In [53]:
# Inventory for Tel Aviv Branch
tel_aviv = pd.Series({
    'MacBook Pro': 5, 
    'LG Screen 27': 1, 
    'Logitech Mouse': 12
})

# Inventory for Haifa Branch
haifa = pd.Series({
    'MacBook Pro': 3, 
    'iPad Air': 7, 
    'Logitech Mouse': 8
})


# ADD another store

# 1 add another store with random items from store 1 , and store 2 and random stock
# 2 input product name from user 
# 3 print the TOTAL items in stock from all 3 stores for the product the user input --> if not exist return 0
# hint: use add + fill_value and is in 
# example:
# first  = pd.Series({'Japan': 100, 'China': 450, 'USA': 250})
# second = pd.Series({'Brazil': 70, 'China': 350, 'USA': 200})
# result = first.add(second, fill_value=0)

modiin = pd.Series ({
    'MacBook Pro': 1, 
    'LG Screen 27': 2,
    'iPad Air': 4
})

total_stock = tel_aviv.add(haifa, fill_value=0).add(modiin, fill_value=0)
print(total_stock)
product = input('product?')
if product.strip() not in total_stock:  # if product.strip() not in total_stock.keys():
    print(0)
else:
    print(total_stock[product.strip()])

LG Screen 27       3.0
Logitech Mouse    20.0
MacBook Pro        9.0
iPad Air          11.0
dtype: float64

product? iPad Air

11.0

In [56]:
tips_df = pd.read_csv('tips.csv')
tips_df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [57]:
type(tips_df)

pandas.core.frame.DataFrame

In [62]:
tips_df = pd.read_csv('tips.csv')
tips_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB

In [65]:
tips_df = pd.read_csv('tips.csv')
print(tips_df.columns)
print(tips_df.index)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')
RangeIndex(start=0, stop=244, step=1)

In [78]:
tips_df = pd.read_csv('tips.csv')
print(len(tips_df))
tips_df.head()
tips_df.tail(5)

244

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
6,8.77,2.00,Male,No,Sun,Dinner,2,4.38,Kristopher Johnson,2223727524230344,Sun5985
7,26.88,3.12,Male,No,Sun,Dinner,4,6.72,Robert Buck,3514785077705092,Sun8157
8,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3522866365840377,Sun6820
9,14.78,3.23,Male,No,Sun,Dinner,2,7.39,Jerome Abbott,3532124519049786,Sun3775
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [84]:
tips_df = pd.read_csv('tips.csv')
tips_df.describe()
#tips_df.describe().transpose()

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [87]:
tips_df = pd.read_csv('tips.csv')
tips_df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [90]:
tips_df = pd.read_csv('tips.csv')
tips_df['tip']
tips_df[ ['tip', 'day'] ]

      tip   day
0    1.01   Sun
1    1.66   Sun
2    3.50   Sun
3    3.31   Sun
4    3.61   Sun
..    ...   ...
239  5.92   Sat
240  2.00   Sat
241  2.00   Sat
242  1.75   Sat
243  3.00  Thur

[244 rows x 2 columns]

In [92]:
tips_df = pd.read_csv('tips.csv')
tips_df['new_column'] = tips_df['tip'] + tips_df['total_bill']
tips_df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,new_column
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,18.00
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,12.00
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,24.51
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,26.99
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,28.20
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,34.95
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,29.18
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,24.67
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,19.57
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,21.78

In [102]:
tips_df = pd.read_csv('tips.csv')
tips_df.drop(1, inplace=True)
tips_df.drop('tip', axis=1, inplace=True)  # remove column 'tip'
tips_df

,total_bill,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
2,21.01,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
5,25.29,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
...,...,...,...,...,...,...,...,...,...,...
239,29.03,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672